### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mp2893** [kmkolasinski/deep-learning-notes#13]
Hi Krzysztof,

I’m interested in using your codes for my project. 
Do you have a license guideline? (Or could you upload a LICENSE file?)

Best,
Ed

**Comment by kmkolasinski** [comment]
Hi, no licence for my code. I would appreciate if you will make any reference or link to my repo. In some cases my implementations were inspired by others works, please check that projects too. On what kind of project you are working?
