### ISSUE TITLE
Do you have Bibtex?

### ISSUE THREAD

**Issue by geosada** [kmkolasinski/deep-learning-notes#23]
Hi Krzysztof,
Is there a bibtex for citation of your Glow code?
If not, I would like to refer to this github url, don’t you mind?

**Comment by kmkolasinski** [comment]
Hi, I'm completely fine with link to this code. May I ask what kind of project do you realize  ?

**Comment by geosada** [comment]
Sure Krzysztof, I’ll definitely let you know if the paper is accepted, though it uses Glow as just a tool of lossless compression so I don’t know if it interests you.
Thanks.

**Comment by kmkolasinski** [comment]
Sure, I would like to take a look, it's definitely an interesting topic.

**Comment by geosada** [comment]
Hi Krzysztof,
A paper using your code has been published in ECCV.
https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123460545.pdf

It was last June, and I apologize for the delay in getting back to you....
Please keep doing great work.
Thanks.

**Comment by kmkolasinski** [comment]
Hi, Geosada it's ok and  congratulations to you and your team! I'm happy my work was useful to you.
