### ISSUE TITLE
Can't find module "neural_ode" in 2.Demo_optimize_bullet_trajectory.ipynb

### ISSUE THREAD

**Issue by Rajivrocks-Ltd** [kmkolasinski/deep-learning-notes#25]
I am trying to run and understand 2.Demo_optimize_bullet_trajectory.ipynb in seminars/2019-03-Neural-Ordinary-Differential-Equations but when I arrive at the line where you want to import a few things from the module "neural_ode" my python install doesn't seem to be able to find it. I tried searching for the module but to no avail. My installed python version is 3.6.8 my tensorflow version is 2.1.0 with cuda version 10.1 and cuDNN 7.6.5

**Comment by kmkolasinski** [comment]
Hi, do you mean this line? 
```
from neural_ode import NeuralODE, defun_neural_ode
```
I so, please make sure from which directory you are running your notebook. If your notebook is in the same directory as `neural_ode.py` it should work. What error you are getting exactly ?

**Comment by Rajivrocks-Ltd** [comment]
Ah, excuse me, I didn't actually download the entire folder. I only downloaded the demo jupyter notebook.
