### ISSUE TITLE
About oversampling-datasets-example.ipynb

### ISSUE THREAD

**Issue by warmestwind** [kmkolasinski/deep-learning-notes#7]
Hi, I just learned your oversampling example, it's help me a lot. And I want to know where the sampling method come from in your example? Can you give me the specific paper name of the sampling method?
Thanks!

**Comment by kmkolasinski** [comment]
Hello, oversampling and undersampling is a popular approach for tackling the class imbalance problem. For sure you can find a lot of materials in the internet about it, like for example this one: https://www.kaggle.com/residentmario/undersampling-and-oversampling-imbalanced-data

**Comment by warmestwind** [comment]
As you suggest, I read some blog about data resampling. But I also want to known the math principles of you example, please give me some more advises ,thanks!

**Comment by kmkolasinski** [comment]
What about this, check also the references in the last paragraph: https://www.marcoaltini.com/blog/dealing-with-imbalanced-data-undersampling-oversampling-and-proper-cross-validation
